-- =====================================================================
-- AI Knowledge Base — initial schema
-- Supabase PostgreSQL + pgvector (0.8+)
--
-- Tables:   documents, document_chunks, conversations, messages
-- Search:   HNSW cosine index + match_document_chunks() RPC
-- Security: Row Level Security on every table (defense in depth; the
--           FastAPI backend also scopes every query to the current user)
-- =====================================================================

-- ---------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------
-- Supabase convention: extensions live in the "extensions" schema,
-- which is on the default search_path.
create extension if not exists vector with schema extensions;


-- ---------------------------------------------------------------------
-- documents
-- ---------------------------------------------------------------------
create table if not exists public.documents (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references auth.users (id) on delete cascade,
    title         text not null,
    filename      text not null,
    storage_path  text,
    summary       text,
    -- Additions beyond the base spec, needed by the UI and pipeline:
    page_count    integer check (page_count >= 0),
    status        text not null default 'processing'
                  check (status in ('processing', 'ready', 'failed')),
    questions     jsonb,                 -- generated suggested questions
    created_at    timestamptz not null default now()
);

create index if not exists documents_user_id_created_at_idx
    on public.documents (user_id, created_at desc);


-- ---------------------------------------------------------------------
-- document_chunks
-- ---------------------------------------------------------------------
create table if not exists public.document_chunks (
    id           uuid primary key default gen_random_uuid(),
    document_id  uuid not null references public.documents (id) on delete cascade,
    content      text not null,
    -- page_number = page where the chunk starts; page_end = page where it
    -- ends. They differ only when a chunk spans a page boundary, so
    -- citations can say "Pages 14–15" instead of guessing one page.
    page_number  integer not null check (page_number >= 1),
    page_end     integer not null check (page_end >= page_number),
    chunk_index  integer not null check (chunk_index >= 0),
    embedding    extensions.vector(1536),
    created_at   timestamptz not null default now(),
    unique (document_id, chunk_index)
);

-- Filter by document (also serves ON DELETE CASCADE lookups).
create index if not exists document_chunks_document_id_idx
    on public.document_chunks (document_id);

-- Approximate nearest-neighbour search with cosine distance.
-- HNSW works on an empty table (unlike IVFFlat, which needs data to train).
create index if not exists document_chunks_embedding_hnsw_idx
    on public.document_chunks
    using hnsw (embedding extensions.vector_cosine_ops);


-- ---------------------------------------------------------------------
-- conversations
-- ---------------------------------------------------------------------
create table if not exists public.conversations (
    id           uuid primary key default gen_random_uuid(),
    user_id      uuid not null references auth.users (id) on delete cascade,
    document_id  uuid not null references public.documents (id) on delete cascade,
    title        text,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()   -- last activity, for history ordering
);

create index if not exists conversations_user_id_updated_at_idx
    on public.conversations (user_id, updated_at desc);
create index if not exists conversations_document_id_idx
    on public.conversations (document_id);


-- ---------------------------------------------------------------------
-- messages
-- ---------------------------------------------------------------------
create table if not exists public.messages (
    id               bigint generated by default as identity primary key,
    conversation_id  uuid not null references public.conversations (id) on delete cascade,
    role             text not null check (role in ('user', 'assistant')),
    content          text not null,
    sources          jsonb,
    created_at       timestamptz not null default now()
);

create index if not exists messages_conversation_id_id_idx
    on public.messages (conversation_id, id);


-- Bump conversations.updated_at whenever a message is added.
create or replace function public.touch_conversation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    update public.conversations
       set updated_at = now()
     where id = new.conversation_id;
    return new;
end;
$$;

drop trigger if exists messages_touch_conversation on public.messages;
create trigger messages_touch_conversation
    after insert on public.messages
    for each row execute function public.touch_conversation();


-- ---------------------------------------------------------------------
-- Vector search RPC
-- ---------------------------------------------------------------------
-- Returns the chunks of ONE document most similar to the query embedding.
-- similarity = 1 - cosine distance (1.0 = identical direction).
--
-- hnsw.iterative_scan (pgvector 0.8+) keeps scanning the HNSW index until
-- enough rows pass the document_id filter. Without it, the index returns
-- its top ef_search candidates across ALL documents and the filter could
-- leave fewer than match_count rows. relaxed_order may return rows slightly
-- out of order, so the outer query re-sorts them.
--
-- SECURITY INVOKER (default): if called with a user's JWT, RLS applies.
create or replace function public.match_document_chunks(
    query_embedding    extensions.vector(1536),
    match_document_id  uuid,
    match_count        integer default 5,
    min_similarity     double precision default 0
)
returns table (
    id           uuid,
    document_id  uuid,
    content      text,
    page_number  integer,
    page_end     integer,
    chunk_index  integer,
    similarity   double precision
)
language sql
stable
set search_path = public, extensions
set hnsw.iterative_scan = relaxed_order
as $$
    select *
    from (
        select
            c.id,
            c.document_id,
            c.content,
            c.page_number,
            c.page_end,
            c.chunk_index,
            1 - (c.embedding <=> query_embedding) as similarity
        from public.document_chunks c
        where c.document_id = match_document_id
          and c.embedding is not null
        order by c.embedding <=> query_embedding
        limit least(greatest(match_count, 1), 50)
    ) ranked
    where ranked.similarity >= min_similarity
    order by ranked.similarity desc;
$$;

revoke execute on function public.match_document_chunks(extensions.vector, uuid, integer, double precision) from public, anon;
grant  execute on function public.match_document_chunks(extensions.vector, uuid, integer, double precision) to authenticated, service_role;


-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
-- The backend uses the service role (bypasses RLS) and enforces ownership
-- itself. These policies make direct access with a user's JWT safe too:
-- a user can only ever see their own rows.

alter table public.documents       enable row level security;
alter table public.document_chunks enable row level security;
alter table public.conversations   enable row level security;
alter table public.messages        enable row level security;

-- documents: full CRUD on own rows
drop policy if exists "documents_select_own" on public.documents;
create policy "documents_select_own" on public.documents
    for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "documents_insert_own" on public.documents;
create policy "documents_insert_own" on public.documents
    for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "documents_update_own" on public.documents;
create policy "documents_update_own" on public.documents
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists "documents_delete_own" on public.documents;
create policy "documents_delete_own" on public.documents
    for delete to authenticated using (user_id = (select auth.uid()));

-- document_chunks: read-only for owners; written only by the backend pipeline
drop policy if exists "document_chunks_select_own" on public.document_chunks;
create policy "document_chunks_select_own" on public.document_chunks
    for select to authenticated using (
        exists (
            select 1 from public.documents d
            where d.id = document_chunks.document_id
              and d.user_id = (select auth.uid())
        )
    );

-- conversations: full CRUD on own rows, only for own documents
drop policy if exists "conversations_select_own" on public.conversations;
create policy "conversations_select_own" on public.conversations
    for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "conversations_insert_own" on public.conversations;
create policy "conversations_insert_own" on public.conversations
    for insert to authenticated with check (
        user_id = (select auth.uid())
        and exists (
            select 1 from public.documents d
            where d.id = conversations.document_id
              and d.user_id = (select auth.uid())
        )
    );

drop policy if exists "conversations_update_own" on public.conversations;
create policy "conversations_update_own" on public.conversations
    for update to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

drop policy if exists "conversations_delete_own" on public.conversations;
create policy "conversations_delete_own" on public.conversations
    for delete to authenticated using (user_id = (select auth.uid()));

-- messages: read and add in own conversations
drop policy if exists "messages_select_own" on public.messages;
create policy "messages_select_own" on public.messages
    for select to authenticated using (
        exists (
            select 1 from public.conversations c
            where c.id = messages.conversation_id
              and c.user_id = (select auth.uid())
        )
    );

drop policy if exists "messages_insert_own" on public.messages;
create policy "messages_insert_own" on public.messages
    for insert to authenticated with check (
        exists (
            select 1 from public.conversations c
            where c.id = messages.conversation_id
              and c.user_id = (select auth.uid())
        )
    );
